name: CI CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - run: sbt assembly

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Set up JDK 1.8
    #     uses: actions/setup-java@v3
    #     with:
    #       java-version: 17
    #   - name: Build Fat Jar
    #     run: sbt assembly
