name: CI CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          check-latest: true
      - name: Build Fat Jar
        run: sbt assembly

      # id: 'auth'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     credentials_json: ${{secrets.GCP_SA_KEY}}

      # id: 'upload-file'
      #   uses: 'google-github-actions/upload-cloud-storage@v1'
      #   with:
      #     path: ''
      #     destination: 'cf-spark-data/file.jar'

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Set up JDK 1.8
    #     uses: actions/setup-java@v3
    #     with:
    #       java-version: 17
    #   - name: Build Fat Jar
    #     run: sbt assembly
