name: CI CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          check-latest: true

      - name: build fat jar
        run: sbt assembly

      - name: deploy to gcs
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: deploy to gcs 2
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "target/scala-2.12/scala template-assembly-3.0.jar"
          destination: "cf-spark-jobs/file.jar"
